#!/usr/bin/env bash
# Canonical launcher. Plugin copies are generated by scripts/sync-kit-assets.py.
set -euo pipefail

fail() { echo "semantic-memory launcher: $*" >&2; exit 64; }
if [ -n "${SEMANTIC_MEMORY_RELAY_PORT:-}" ]; then
  fail "SEMANTIC_MEMORY_RELAY_PORT is no longer supported; configure an explicit upstream transport instead"
fi
SM_BIN="${SEMANTIC_MEMORY_MCP_BIN:-}"
if [ -n "$SM_BIN" ]; then
  [ -f "$SM_BIN" ] && [ -x "$SM_BIN" ] || fail "configured SEMANTIC_MEMORY_MCP_BIN is not executable"
else
  SM_BIN="$(command -v semantic-memory-mcp 2>/dev/null || true)"
  for candidate in "$HOME/.local/bin/semantic-memory-mcp" "$HOME/.cargo/bin/semantic-memory-mcp"; do
    if [ -z "$SM_BIN" ] && [ -f "$candidate" ] && [ -x "$candidate" ]; then SM_BIN="$candidate"; fi
  done
fi
[ -n "$SM_BIN" ] || { echo "semantic-memory-mcp not found; set SEMANTIC_MEMORY_MCP_BIN to a verified build" >&2; exit 127; }
HELP="$("$SM_BIN" --help 2>&1)" || fail "configured binary failed --help"
ARGS=()
add() {
  local flag="$1" value="${2:-}"
  # Match complete option tokens, not prefixes such as --http-port-extra.
  if ! printf '%s\n' "$HELP" | grep -Eq -- "(^|[[:space:],])${flag}([[:space:]=,]|$)"; then
    fail "configured binary does not support required option $flag"
  fi
  ARGS+=("$flag")
  if [ "$#" -eq 2 ]; then ARGS+=("$value"); fi
}
optional() { local value="${!1:-}"; [ -z "$value" ] || add "$2" "$value"; }
boolean() {
  local value="${!1:-0}"
  case "$value" in 0|false|'') ;; 1|true) add "$2" ;; *) fail "$1 must be 0, 1, false, or true" ;; esac
}
SM_DIR="${SEMANTIC_MEMORY_DIR:-${SM_KIT_DEFAULT_DIR:-$HOME/.local/share/semantic-memory}}"
[ ! -e "$SM_DIR" ] || [ -d "$SM_DIR" ] || fail "SEMANTIC_MEMORY_DIR must be a directory; no migration was attempted"
add --memory-dir "$SM_DIR"
add --embedder "${SEMANTIC_MEMORY_EMBEDDER:-candle}"
add --tool-profile "${SEMANTIC_MEMORY_TOOL_PROFILE:-${SM_KIT_DEFAULT_PROFILE:-lean}}"
optional SEMANTIC_MEMORY_EMBEDDING_URL --embedding-url
optional SEMANTIC_MEMORY_EMBEDDING_MODEL --embedding-model
optional SEMANTIC_MEMORY_EMBEDDING_DIMS --embedding-dims
optional SEMANTIC_MEMORY_LLM_MODEL --llm-model
optional SEMANTIC_MEMORY_OPERATOR_AUTHORITY_TOKEN_FILE --operator-authority-token-file
optional SEMANTIC_MEMORY_HTTP_AUTH_TOKEN_FILE --http-auth-token-file
optional SEMANTIC_MEMORY_MCP_HTTP_TOKEN_FILE --mcp-http-token-file
for item in 'SEMANTIC_MEMORY_HTTP_PORT:--http-port' 'SEMANTIC_MEMORY_MCP_HTTP_PORT:--mcp-http-port'; do
  var="${item%%:*}"; flag="${item#*:}"; value="${!var:-0}"
  [ "$value" = 0 ] || [ -z "$value" ] || add "$flag" "$value"
done
# Upstream validates token contents, transport permissions, and model/codec support.
boolean SEMANTIC_MEMORY_TURBO_QUANT --turbo-quant
optional SEMANTIC_MEMORY_TURBO_QUANT_BITS --turbo-quant-bits
optional SEMANTIC_MEMORY_TURBO_QUANT_PROJECTIONS --turbo-quant-projections
optional SEMANTIC_MEMORY_MNEMES_DEVICE_ID --mnemes-device-id
optional SEMANTIC_MEMORY_MNEMES_STORE_ID --mnemes-store-id
optional SEMANTIC_MEMORY_MNEMES_STREAM_EPOCH --mnemes-stream-epoch
boolean SEMANTIC_MEMORY_MNEMES_REQUIRED --mnemes-required
exec "$SM_BIN" "${ARGS[@]}" "$@"
