#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export SEMANTIC_MEMORY_TOOL_PROFILE="${SEMANTIC_MEMORY_ADMIN_TOOL_PROFILE:-full}"
export SEMANTIC_MEMORY_HTTP_PORT="${SEMANTIC_MEMORY_ADMIN_HTTP_PORT:-0}"
export SEMANTIC_MEMORY_MCP_HTTP_PORT="${SEMANTIC_MEMORY_ADMIN_MCP_HTTP_PORT:-0}"
exec "$SCRIPT_DIR/run-server.sh" "$@"
